// tests/impl_tech_front.js — vues techniques (rapport du jour, historique, compilation) + routes + CSS
const fs = require('fs');
const path = require('path');
const out = [];
let miss = 0;

const vf = path.join(__dirname, '..', 'public', 'js', 'views.js');
let v = fs.readFileSync(vf, 'utf8');

// 1. Vues techniques insérées avant l'export final
const exportIdx = v.indexOf('window.TAKATA_VIEWS = {');
if (exportIdx === -1) { out.push('  ⚠️ views: export TAKATA_VIEWS non trouvé'); process.exit(1); }
const techViews = [
  "  // ============ RAPPORTS TECHNIQUES (métier : évacuations, désinfections) ============",
  "  async function techDayView() {",
  "    const me = TAKATA.store.user || {};",
  "    const today = new Date().toISOString().slice(0, 10);",
  "    const prods = ((await get('/products')) || []).filter((p) => p.category === 'Intrant');",
  "    return `",
  "      <div class=\"page-title\">Rapport du jour — ${esc(me.full_name || '')}</div>",
  "      <form class=\"card\" onsubmit=\"return TAKATA_VIEWS.submitTechReport(event)\">",
  "        <div class=\"field\"><label for=\"t-date\">Date du rapport</label><input id=\"t-date\" type=\"date\" value=\"${today}\"></div>",
  "        <div class=\"row\">",
  "          <div class=\"field\"><label for=\"t-menages\">Ménages servis</label><input id=\"t-menages\" type=\"number\" min=\"0\" value=\"0\"></div>",
  "          <div class=\"field\"><label for=\"t-poubelles\">Poubelles évacuées</label><input id=\"t-poubelles\" type=\"number\" min=\"0\" value=\"0\"></div>",
  "        </div>",
  "        <div class=\"row\">",
  "          <div class=\"field\"><label for=\"t-courses\">Courses de camion vers la décharge</label><input id=\"t-courses\" type=\"number\" min=\"0\" value=\"0\"></div>",
  "          <div class=\"field\"><label for=\"t-desinf\">Désinfections faites</label><input id=\"t-desinf\" type=\"number\" min=\"0\" value=\"0\"></div>",
  "        </div>",
  "        <div class=\"field\"><label for=\"t-maisons\">Maisons désinfectées</label><input id=\"t-maisons\" type=\"number\" min=\"0\" value=\"0\"></div>",
  "        <div class=\"section-title\">Produits utilisés et état de besoin</div>",
  "        ${prods.map((p) => `<div class=\"row\">",
  "          <div class=\"field\"><label for=\"t-q-${p.id}\">${esc(p.name)} — utilisé</label><input id=\"t-q-${p.id}\" type=\"number\" min=\"0\" value=\"0\" step=\"any\"></div>",
  "          <div class=\"field\"><label for=\"t-b-${p.id}\">État de besoin (à commander)</label><input id=\"t-b-${p.id}\" type=\"number\" min=\"0\" value=\"0\" step=\"any\"></div>",
  "        </div>`).join('') || emptyState('box', 'Aucun produit intrant au catalogue')}",
  "        <div class=\"field\"><label for=\"t-comment\">Observations de terrain</label><textarea id=\"t-comment\" rows=\"4\" placeholder=\"Ex. : incidents de la tournée, état du matériel, remarques…\"></textarea></div>",
  "        <button class=\"btn\" type=\"submit\">${icon('check', 16)} Enregistrer le rapport du jour</button>",
  "      </form>`;",
  "  }",
  "",
  "  async function submitTechReport(e) {",
  "    e.preventDefault();",
  "    const items = [];",
    "    document.querySelectorAll('[id^=\"t-q-\"]').forEach((inp) => {",
  "      const pid = Number(inp.id.replace('t-q-', ''));",
  "      const qte = Number(inp.value) || 0;",
  "      const besInput = document.getElementById('t-b-' + pid);",
  "      const bes = Number(besInput && besInput.value) || 0;",
  "      if (qte > 0 || bes > 0) items.push({ product_id: pid, quantite_utilisee: qte, etat_de_besoin: bes });",
  "    });",
  "    const body = {",
  "      date: document.getElementById('t-date').value,",
  "      menages_servis: Number(document.getElementById('t-menages').value) || 0,",
  "      poubelles_evacuees: Number(document.getElementById('t-poubelles').value) || 0,",
  "      courses_camion: Number(document.getElementById('t-courses').value) || 0,",
  "      desinfections: Number(document.getElementById('t-desinf').value) || 0,",
  "      maisons_desinfectees: Number(document.getElementById('t-maisons').value) || 0,",
  "      commentaire: document.getElementById('t-comment').value,",
  "      items",
  "    };",
  "    try {",
  "      const r = await TAKATA.offlineAware('POST', '/tech/reports', body);",
  "      toast(r && r.queued ? 'Rapport enregistré hors-ligne (sera synchronisé)' : 'Rapport du jour enregistré ✅');",
  "      location.hash = '#/tech/historique';",
  "    } catch (err) { toast(err.message || 'Erreur', true); }",
  "    return false;",
  "  }",
  "",
  "  async function techHistoryView() {",
  "    const reports = await get('/tech/reports');",
  "    if (reports === null) return emptyState('wifiOff', 'Hors ligne — réessayez plus tard');",
  "    return `",
  "      <div class=\"page-title\">Mes rapports techniques</div>",
  "      <div class=\"list\">",
  "        ${reports.map((r) => `<a class=\"list-item\" href=\"#/tech/rapport/${r.id}\">",
  "          <div class=\"avatar\">${icon('truck', 18)}</div>",
  "          <div class=\"body\"><div class=\"title\">${date(r.date)}</div>",
  "          <div class=\"desc\">${r.menages_servis} ménage(s) · ${r.poubelles_evacuees} poubelle(s) · ${r.courses_camion} course(s) camion${r.desinfections ? ' · ' + r.desinfections + ' désinfection(s)' : ''}</div></div>",
  "          <div class=\"chevron\">›</div></a>`).join('') || emptyState('truck', 'Aucun rapport enregistré — créez le rapport du jour')}",
  "      </div>`;",
  "  }",
  "",
  "  async function techReportDetailView(params) {",
  "    const reports = await get('/tech/reports');",
  "    const r = (reports || []).find((x) => x.id === Number(params.id));",
  "    if (!r) return emptyState('truck', 'Rapport introuvable');",
  "    return `",
  "      <div class=\"page-title\">Rapport du ${date(r.date)}</div>",
  "      <div class=\"card\">",
  "        <div class=\"kv\"><span>Technicien</span><b>${esc(r.technicien)}</b></div>",
  "        <div class=\"kv\"><span>Ménages servis</span><b>${r.menages_servis}</b></div>",
  "        <div class=\"kv\"><span>Poubelles évacuées</span><b>${r.poubelles_evacuees}</b></div>",
  "        <div class=\"kv\"><span>Courses de camion vers la décharge</span><b>${r.courses_camion}</b></div>",
  "        <div class=\"kv\"><span>Désinfections faites</span><b>${r.desinfections}</b></div>",
  "        <div class=\"kv\"><span>Maisons désinfectées</span><b>${r.maisons_desinfectees}</b></div>",
  "        ${r.commentaire ? `<hr class=\"divider\"><div class=\"muted\">Observations de terrain : ${esc(r.commentaire)}</div>` : ''}",
  "      </div>",
  "      ${(r.items || []).length ? `<div class=\"section-title\">Produits utilisés</div><div class=\"list\">",
  "        ${r.items.map((it) => `<div class=\"list-item\" style=\"cursor:default\"><div class=\"body\"><div class=\"title\">${esc(it.produit)}</div>",
  "        <div class=\"desc\">Utilisé : ${it.quantite_utilisee} · État de besoin : ${it.etat_de_besoin}</div></div></div>`).join('')}</div>` : ''}`;",
  "  }",
  "",
  "  async function techCompilationView() {",
  "    const s = await get('/tech/summary');",
  "    if (s === null) return emptyState('wifiOff', 'Hors ligne — réessayez plus tard');",
  "    return `",
  "      <div class=\"page-title\">Compilation technique</div>",
  "      <div class=\"stats\">",
  "        <div class=\"stat\"><div class=\"num\">${s.totals.menages_servis}</div><div class=\"lbl\">Ménages servis</div></div>",
  "        <div class=\"stat\"><div class=\"num\">${s.totals.poubelles_evacuees}</div><div class=\"lbl\">Poubelles évacuées</div></div>",
  "        <div class=\"stat\"><div class=\"num\">${s.totals.courses_camion}</div><div class=\"lbl\">Courses camion</div></div>",
  "        <div class=\"stat\"><div class=\"num\">${s.totals.desinfections}</div><div class=\"lbl\">Désinfections</div></div>",
  "        <div class=\"stat\"><div class=\"num\">${s.totals.maisons_desinfectees}</div><div class=\"lbl\">Maisons désinfectées</div></div>",
  "      </div>",
  "      <div class=\"section-title\">Par technicien</div>",
  "      <div class=\"list\">",
  "        ${(s.per_tech || []).map((x) => `<div class=\"list-item\" style=\"cursor:default\"><div class=\"avatar\">${icon('truck', 18)}</div>",
  "          <div class=\"body\"><div class=\"title\">${esc(x.technicien)}${x.region ? ' · ' + esc(x.region) : ''}</div>",
  "          <div class=\"desc\">${x.menages_servis} ménage(s) · ${x.poubelles_evacuees} poubelle(s) · ${x.courses_camion} course(s) camion · ${x.desinfections} désinfection(s) · ${x.maisons_desinfectees} maison(s) · ${x.nb_rapports} rapport(s)</div></div></div>`).join('') || emptyState('truck', 'Aucun rapport')}",
  "      </div>",
  "      <div class=\"section-title\">Produits consommés, stocks et états de besoin</div>",
  "      <div class=\"list\">",
  "        ${(s.consos || []).map((c) => `<div class=\"list-item\" style=\"cursor:default\">",
  "          <div class=\"body\"><div class=\"title\">${esc(c.produit)}</div>",
  "          <div class=\"desc\">Utilisé : ${c.quantite_utilisee} · État de besoin : ${c.etat_de_besoin} · En stock : ${c.quantite_en_stock}</div></div>",
  "          ${c.etat_de_besoin > c.quantite_en_stock ? '<span class=\"badge red\">À commander</span>' : '<span class=\"badge green\">OK</span>'}</div>`).join('') || emptyState('box', 'Aucune consommation enregistrée')}",
  "      </div>`;",
  "  }",
  "",
  "  window.TAKATA_VIEWS = {"
].join('\n');
v = v.slice(0, exportIdx) + techViews + v.slice(exportIdx + 'window.TAKATA_VIEWS = {'.length);
out.push('  views: vues techniques insérées avant l\'export');

// 2. Exports
v = v.replace(
  "    loginView, submitLogin, togglePassword, dashboardView,",
  "    loginView, submitLogin, togglePassword, techDayView, submitTechReport, techHistoryView, techReportDetailView, techCompilationView, dashboardView,"
);
out.push('  views: exports techniques ajoutés');

fs.writeFileSync(vf, v, 'utf8');
console.log(out.join('\n'));
console.log(miss ? 'IMPL TECH PARTIELLE' : 'IMPL TECH OK');